const ROLES = {
  STUDENT: 'STUDENT',
  OWNER: 'OWNER',
  DELIVERY: 'DELIVERY',
}

const MEAL_TYPES = {
  BREAKFAST: 'BREAKFAST',
  LUNCH: 'LUNCH',
  DINNER: 'DINNER',
}

const FOOD_CATEGORY = {
  VEG: 'VEG',
  NONVEG: 'NONVEG',
  EGG: 'EGG',
  VEGAN: 'VEGAN',
}

const MESS_CATEGORY = {
  PURE_VEG: 'PURE_VEG',
  NONVEG: 'NONVEG',
  BOTH: 'BOTH',
}

const SUBSCRIPTION_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  PAUSED: 'PAUSED',
}

const PAYMENT_STATUS = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
}

const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  HOLIDAY: 'HOLIDAY',
}

const DELIVERY_STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
}

const PLAN_DURATION = {
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  CUSTOM: 'CUSTOM',
}

module.exports = {
  ROLES,
  MEAL_TYPES,
  FOOD_CATEGORY,
  MESS_CATEGORY,
  SUBSCRIPTION_STATUS,
  PAYMENT_STATUS,
  ATTENDANCE_STATUS,
  DELIVERY_STATUS,
  PLAN_DURATION,
}